shell/git: update git pre-commit and add git-copy-hooks

diff --git a/shell/git/template/hooks/pre-commit b/shell/git/template/hooks/pre-commit
--- a/shell/git/template/hooks/pre-commit
+++ b/shell/git/template/hooks/pre-commit
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
+# ========================= GIT-SECRETS ========================
+# git secrets --install ~/.templates/git-secrets
+git secrets --pre_commit_hook -- "$@" || exit 1
+
 # ========================= PRE-COMMIT ========================
+# pre-commit init-templatedir ~/.templates/pre-commit
 # start templated
 ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit --skip-on-missing-config)
 # end templated
@@ -8,12 +13,8 @@ HERE="$(cd "$(dirname "$0")" && pwd)"
 ARGS+=(--hook-dir "$HERE" -- "$@")
 
 if command -v pre-commit > /dev/null; then
+    echo "${ARGS[@]}"
     exec pre-commit "${ARGS[@]}"
 else
-    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
-    exit 1
+    echo '`pre-commit` not found. Skipping pre-commit.' 1>&2
 fi
-
-# ========================= GIT-SECRETS ========================
-git secrets --pre_commit_hook -- "$@"
-
